name: Update Assets and Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make script executable
        run: chmod +x generate-sw.sh

      - name: Update Service Worker
        run: ./generate-sw.sh

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # On vérifie s'il y a des changements avant de commit
          if [ -n "$(git status --porcelain)" ]; then
            git add service-worker.js
            git commit -m "chore: auto-update service worker assets [skip ci]"
            git push
          else
            echo "Aucun changement détecté."
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
